### ISSUE TITLE
My keyboard has no "home" key 😅

### ISSUE THREAD

**Issue by oalders** [saiftynet/Calendar#1]
Supposedly `fn`+`⬅️ should substitute for "home", but that doesn't seem to do the trick for me. At any rate, might be handy to add an alternate shortcut for those of us with keyboards which helpfully have removed this key.

I should add that I guess I could remap the keyboard, but that seems like a fair amount of overhead just to mess around. 😄

**Comment by saiftynet** [comment]
OK I will make the keys user configurable.

**Comment by saiftynet** [comment]
Version 0.09 allows the "t" key to go to today's date.   Not sure the best way to make key mapping configurable in an intuitive way.

**Comment by oalders** [comment]
Thanks, @saiftynet!
